project_id = "eucjeggfclztkbbupaav"

[functions.delete-user]
verify_jwt = false

[functions.lookup-participant]
verify_jwt = false

[functions.wa-delivery-webhook]
verify_jwt = false

[functions.courier-webhook]
verify_jwt = false

[functions.bonvoice-webhook]
verify_jwt = false
