// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eucjeggfclztkbbupaav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1Y2plZ2dmY2x6dGtiYnVwYWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk0Nzk1NzIsImV4cCI6MjA5NTA1NTU3Mn0.nVHEPuXB5cKzD8OiFu1TIVyC6m4nfovw_nUJOZt5TA4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom storage for Windows compatibility
const customStorage = {
  getItem: (key: string) => {
    try {
      return localStorage.getItem(key);
    } catch (error) {
      console.warn('LocalStorage getItem failed, using sessionStorage:', error);
      try {
        return sessionStorage.getItem(key);
      } catch (sessionError) {
        console.warn('SessionStorage also failed:', sessionError);
        return null;
      }
    }
  },
  setItem: (key: string, value: string) => {
    try {
      localStorage.setItem(key, value);
    } catch (error) {
      console.warn('LocalStorage setItem failed, using sessionStorage:', error);
      try {
        sessionStorage.setItem(key, value);
      } catch (sessionError) {
        console.warn('SessionStorage setItem also failed:', sessionError);
      }
    }
  },
  removeItem: (key: string) => {
    try {
      localStorage.removeItem(key);
    } catch (error) {
      console.warn('LocalStorage removeItem failed, using sessionStorage:', error);
      try {
        sessionStorage.removeItem(key);
      } catch (sessionError) {
        console.warn('SessionStorage removeItem also failed:', sessionError);
      }
    }
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: customStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});